package com.example;

import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }

    /**
     * Returns a string array containing all captured windows of reference_string.
     * 
     * The first window generated by the algorithm will be of the same size as
     * reference_string. Afterwards, the window size will decrement by 1 and
     * slide across reference_string. The algorithm will iterate by sliding the
     * window across reference_string by each character, then shrink the window by 1
     * until its size reaches 2.
     * 
     * @param reference_string the string where the window will slide across
     * @return a string array containing all captured windows of the algorithm
     */
    public static String[] decrementingSlidingWindow(String reference_string) {
        int reference_string_length = reference_string.length();
        int window_start = 0;
        int window_end = reference_string.length();
        int window_size = window_end - window_start;

        ArrayList<String> output = new ArrayList<>();

        while (window_size > 1) {
            while (reference_string_length >= window_start + window_size) {
                String window_value = reference_string.substring(window_start, window_start + window_size);

                output.add(window_value); // You can do whatever here. I chose to save the window here

                window_start++; // Move the window across relative to reference_string
            }
            window_size--;
            window_start = 0; // Reset relative to reference_string by moving the window to the start
        }

        return output.toArray(new String[0]);
    }
}
